---
  - name: Copy ssh id to managed hosts
    hosts: server
    tags: init
    roles:
      - role: init_role
      

  - name:
    hosts: server
    tags: config
    tasks: 
      - name: Get Ping
        ping:
